[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[general]
import = ["~/.config/alacritty/alacritty_themes/gruvchad.toml"]
working_directory = "None"

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular" 
bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold" 
italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic" 
size = 12.8
offset.y=1

[terminal]
shell.program = "/bin/zsh"

[window]
decorations = "Buttonless"
padding.x = 10
padding.y = 6
dynamic_padding = true
opacity = 0.78
blur = true

[cursor]
style.blinking = "Off"
blink_interval = 500
