[colors.primary]
background = "#faf4ed"
foreground = "#575279"
dim_foreground = "#797593"
bright_foreground = "#423e5b"

[colors.cursor]
text = "#faf4ed"
cursor = "#575279"

[colors.vi_mode_cursor]
text = "#faf4ed"
cursor = "#575279"

[colors.search.matches]
foreground = "#faf4ed"
background = "#56949f"

[colors.search.focused_match]
foreground = "#faf4ed"
background = "#907aa9"

[colors.footer_bar]
foreground = "#faf4ed"
background = "#56949f"

[colors.hints.start]
foreground = "#faf4ed"
background = "#d7827e"

[colors.hints.end]
foreground = "#faf4ed"
background = "#ea9d34"

[colors.selection]
text = "#faf4ed"
background = "#575279"

[colors.normal]
black = "#faf4ed"
red = "#b4637a"
green = "#56949f"
yellow = "#d7827e"
blue = "#907aa9"
magenta = "#ea9d34"
cyan = "#286983"
white = "#575279"

[colors.bright]
black = "#9893a5"
red = "#b4637a"
green = "#56949f"
yellow = "#d7827e"
blue = "#907aa9"
magenta = "#ea9d34"
cyan = "#286983"
white = "#423e5b"
[[colors.indexed_colors]]
index = 16
color = "#A39EAD"


