all:
	(cd cpu_load && $(MAKE))
	(cd memory_load && $(MAKE))
	(cd hdd_load && $(MAKE))
	(cd weather_info && $(MAKE))
	(cd network_load && $(MAKE))
	(cd media_player && $(MAKE))
	(cd apple_menu && $(MAKE))
